apiVersion: v2
name: spring-playground
description: A Helm chart for Spring Boot Playground application
type: application
version: 0.1.0
appVersion: "0.0.1-SNAPSHOT"

maintainers:
  - name: anhkhoa289

dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
